### ISSUE TITLE
Neue Spalte "Todesfaelle_gesamt" möglich?

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#1]
Mit der Einstellung des COVID-19 Dashboards und anscheinend wohl auch des COVID-19 Datenhubs bei arcgis ist es deutlich schwerer geworden die Frage "Wieviele COVID Todesfälle gab es in Kreis X" zu beantworten.

(Hintergrund: ich verwende u.a. diese Zahl um unter https://coronamuc.de die Dunkelziffer auf IFR Basis abzuschätzen)

Die momentan einzige Möglichkeit scheint sich regelmäßig die 385 MB von https://github.com/robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland/blob/main/COVID-19-Faelle_7-Tage-Inzidenz_Landkreise.csv zu holen, dort auf alle Zeilen mit der entsprechenden Landkreis ID zu filtern um dann die Summe zu bilden.

Das sind knapp 2GB Download in der Woche (5 Tage mal 380 MB) nur um diese Zahl zu bekommen. 

https://github.com/robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland erlaubt es nicht auf Kreisebene zu filtern, da dort nur auf Landes- und Bundesebene aggregiert wird.

Daher meine Frage: Wäre es möglich in diesem Repository eine neue Spalte Todesfaelle_gesamt anzulegen, damit man diese Zahl schnell und einfach(er) ermitteln kann?

**Comment by Rubber1Duck** [comment]
Hallo,
schau mal noch der api von Marlon Lückert, https://api.corona-zahlen.org, dort solltest du alles finden was du suchst!
z.B. https://api.corona-zahlen.org/districts/05119 (https://api.corona-zahlen.org/districts/XXXXX XXXXX=AGS)

```json
{"data":{"05119":{"ags":"05119","name":"Oberhausen","county":"SK Oberhausen","state":"Nordrhein-Westfalen","population":208752,"cases":76646,"deaths":576,"casesPerWeek":3,"deathsPerWeek":0,"stateAbbreviation":"NW","recovered":76065,"weekIncidence":1.4371119797654635,"casesPer100k":36716.29493370123,"delta":{"cases":0,"deaths":0,"recovered":0,"weekIncidence":-0.479037326588}}},"meta":{"source":"Robert Koch-Institut","contact":"Marlon Lueckert (m.lueckert@me.com)","info":"https://github.com/marlon360/rki-covid-api","lastUpdate":"2023-07-28T01:04:08.000Z","lastCheckedForUpdate":"2023-07-28T06:37:24.674Z"}}
```
