### ISSUE TITLE
2023-10-12 kein Update

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#13]
Kommt da heute noch ein Update oder erst morgen?

**Comment by RKIOpenData** [comment]
Hallo @jwildeboer,

die Daten kamen heute leider etwas sp'ter. Da der Upload aber durch ist schlie-e ich dieses Issue erstmal

viele Grüße
Knut Perseke
für das Team RKI | Open Data
