### ISSUE TITLE
Fehlende Fallzahlen am 19.12.23

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#17]
Mit Meldedatum 19.12. wurden 0 Fälle gemeldet. Ist das richtig?

**Comment by HannesWuensche** [comment]
Hallo @Rutger265, 

vielen Dank für den Hinweis. Wir gehen der Sache nach. 
Die Ursache scheint bei den Übermittlungen zu liegen: 

https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/issues/12

Beste Grüße
@HannesWuensche
