### ISSUE TITLE
2024-01-09 Update verspätet?

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#18]
Um 10:27 immer noch Stand gestern bei den Daten?

Jan

**Comment by jwildeboer** [comment]
14:16 und noch immer keine neuen Zahlen. Morgen dann hoffentlich wieder.

**Comment by Anna-Lyst** [comment]
Wie Jan schon feststellte, das scheint heute (Mo, 09.01.) _mal wieder_ nichts mehr zu werden ... nun ist es 17:00 Uhr ...

Liebes **RKIOpenData**-Team: sind im RKI derzeit noch immer sooo viele erkrankt oder woran happert's heute? Eine _kurze Erklärung_ wäre **nett** - _Vielen Dank!_ ... schließlich warten doch noch zahlreiche auf die täglichen GitHub-Daten zur weiteren Auswertung und Verbreitung - wenn schon die 'offiziellen' RKI-Darstellungen seit längerem nicht mehr an die breitere Öffentlichkeit dringen ...

(Muß wohl dieser "hamlose Schnupfen" sein, der doch sooo "mild" ausfallen soll ... )

**Comment by RKIOpenData** [comment]
Liebe User,

vielen Dank für euer Feedback. Leider gab es wie ihr schon festgestellt habt Probleme bei der Datengenerierung heute. Die aktualisierten Daten sind jetzt hochgeladen

Beste Grüße
Knut Perseke
für das Team RKI | Open Data
