### ISSUE TITLE
24.01.2024: Heute wieder keine Aktualisierung?

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#19]
Betrifft anscheinend alle Repositories

**Comment by RKIOpenData** [comment]
Hallo @Rutger265 ,

leider gab es ein technisches Problem, deshalb haben sich die Daten heute etwas verspätet.

viele Grüße
Knut Perseke | für das Team RKI Open Data
