### ISSUE TITLE
Auch heute (3.2.24) morgens kein Update 

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#21]

**Comment by RKIOpenData** [comment]
Hallo @Rutger265,

danke für dein Feedback. Am 03.02.2024 gab es leider ein Problem mit der Datenbereitstellung. Da die Daten in den letzten Tagen wieder verfügbar waren würde ich das Ticket hier schließen.

beste Grüße
Knut Perseke für das Team | RKI Open Data
