### ISSUE TITLE
Kein Update am 22.10.24 ?

### ISSUE THREAD

**Issue by HorstErnst** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#31]

**Comment by SimonScholler** [comment]
Hallo,

leider nein, Ich gebe Bescheid, sobald die Daten wieder vorliegen.

Viele Grüße
Simon | RKI Open Data Team

**Comment by SimonScholler** [comment]
Hallo,
die Daten liegen nun für heute wieder vor.
Viele Grüße
Simon | RKI Open Data Team
