### ISSUE TITLE
2023-07-16 kein Update?

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#4]
Normalerweise kommen die Updates früh am morgen, heute aber auch um 11:30 noch keine neuen Zahlen.

Jan

**Comment by RKIOpenData** [comment]
Hi Jan,

gestern gab es leider ein Problem bei der Datenbereitstellung. Da die aktuellen Zahlen jetzt wieder da sind schließe ich das Ticket.

viele Grüße
Knut Perseke
für das RKI Open Data Team
