### ISSUE TITLE
Update 23-08-25: Wirklich Null neue Fallmeldungen??

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland#7]

**Comment by jwildeboer** [comment]
Siehe https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/issues/8 - es scheint seit 3 Tagen Probleme mit der Meldungsverarbeitung bei SurvNet zu geben.

**Comment by RKIOpenData** [comment]
Hi @Rutger265,

es gab leider technische Probleme mit der Bereitstellung der Daten. Jetzt sollte wieder alles funktionieren.

viele Grüße
Knut Perseke
für das Team RKI | Open Data
